export enum MedicalSpecialty {
  ENDOSCOPIA = "Endoscopia",
  GASTROENTEROLOGIA = "Gastroenterologia",
  GERIATRIA = "Geriatria",
  GINECOLOGIA_OBSTETRICIA = "Ginecologia e Obstetrícia",
  HEMATOLOGIA = "Hematologia e Hemoterapia",
  HEPATOLOGIA = "Hepatologia",
  HOMEOPATIA = "Homeopatia",
  INFECTOLOGIA = "Infectologia",
  MASTOLOGIA = "Mastologia",
  MEDICINA_DE_EMERGENCIA = "Medicina de Emergência",
  MEDICINA_DO_ESPORTE = "Medicina do Esporte",
  MEDICINA_DO_TRABALHO = "Medicina do Trabalho",
  MEDICINA_DE_FAMILIA = "Medicina de Família e Comunidade",
  MEDICINA_FISICA_REABILITACAO = "Medicina Física e Reabilitação",
  MEDICINA_INTENSIVA = "Medicina Intensiva",
  MEDICINA_LEGAL = "Medicina Legal e Perícia Médica",
  NEFROLOGIA = "Nefrologia",
  NEUROCIRURGIA = "Neurocirurgia",
  NEUROLOGIA = "Neurologia",
  NUTROLOGIA = "Nutrologia",
  OFTALMOLOGIA = "Oftalmologia",
  ONCOLOGIA_CLINICA = "Oncologia Clínica",
  ORTOPEDIA_TRAUMATOLOGIA = "Ortopedia e Traumatologia",
  OTORRINOLARINGOLOGIA = "Otorrinolaringologia",
  PATOLOGIA = "Patologia",
  PATOLOGIA_CLINICA = "Patologia Clínica/Medicina Laboratorial",
  PEDIATRIA = "Pediatria",
  PNEUMOLOGIA = "Pneumologia",
  PSIQUIATRIA = "Psiquiatria",
  RADIOLOGIA = "Radiologia e Diagnóstico por Imagem",
  RADIOTERAPIA = "Radioterapia",
  REUMATOLOGIA = "Reumatologia",
  UROLOGIA = "Urologia",
  ALERGOLOGIA = "Alergologia",
  ANGIOLOGIA = "Angiologia",
  CARDIOLOGIA = "Cardiologia",
  CIRURGIA_GERAL = "Cirurgia Geral",
  CIRURGIA_PLASTICA = "Cirurgia Plástica",
  DERMATOLOGIA = "Dermatologia",
  ENDOCRINOLOGIA_METABOLOGIA = "Endocrinologia e Metabologia",
  FISIATRIA = "Fisiatria",
  GENETICA_MEDICA = "Genética Médica",
  GERIATRIA_E_CUIDADOS_PALIATIVOS = "Geriatria e Cuidados Paliativos",
  HEMOTERAPIA = "Hemoterapia",
  MEDICINA_NUCLEAR = "Medicina Nuclear",
  NEUROFISIOLOGIA_CLINICA = "Neurofisiologia Clínica",
  OBSTETRICIA = "Obstetrícia",
  ONCOLOGIA_PEDIATRICA = "Oncologia Pediátrica",
  ORTOPEDIA_PEDIATRICA = "Ortopedia Pediátrica",
  PATOLOGIA_ANATOMICA = "Patologia Anatômica",
  RADIOLOGIA_INTERVENCIONISTA = "Radiologia Intervencionista",
  SAUDE_COLETIVA = "Saúde Coletiva",
  TERAPIA_INTENSIVA_PEDIATRICA = "Terapia Intensiva Pediátrica",
}

export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  }),
);
